python-dotenv
pytube
youtube_transcript_api
pymupdf
sentence-transformers
openai
os
spacy
https://github.com/explosion/spacy-models/releases/download/it_core_news_sm-3.0.0/it_core_news_sm-3.0.0.tar.gz#egg=it_core_news_sm==3.0.0
chromadb